services:

  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env.docker.test

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - back-end/.env.docker.test