name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Creating backend env test file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: ${{ secrets.API_PORT }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV_TEST }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_DOCKER_TEST_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB_DOCKER_TEST }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL_DOCKER_TEST }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_LOCALE: ${{ secrets.LOCALE }}
          file_name: .env.docker.test
          directory: back-end/
          fail_on_empty: true

      - name: Run Docker Container Tests
        run: docker-compose -f docker-compose-tests.yml run node_app npm run test
